[project]
name = "grading-helper-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mkdocs-material>=9.6.23",
    "pre-commit>=4.5.0",
]

[dependency-groups]
dev = [
    "ruff>=0.14.8",
]
